spring:
    application:
        name: units-booking-service
    datasource:
        url: jdbc:h2:mem:bookingsystem;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /v3/api-docs

liquibase:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password: password
    change-log: classpath:db/changelog/db.changelog-master.yaml